[variables]
    PHP_VERSION = '8.3'

[phases.setup]
    nixPkgs = ['php83', 'php83Packages.composer', 'nodejs']

[phases.install]
    cmds = ['composer install --frozen-lockfile --no-dev']

[phases.build]
    cmds = ['php artisan optimize']